# Dockerfile para el Portal Web de Gestión de PostgreSQL (PgAdmin 4)
FROM dpage/pgadmin4:latest

# Variables de entorno por defecto para PgAdmin
ENV PGADMIN_DEFAULT_EMAIL=admin@geoapp.com
ENV PGADMIN_DEFAULT_PASSWORD=admin123
ENV PGADMIN_LISTEN_PORT=80

EXPOSE 80
